framework:
    messenger:
        reset_on_message: true
        transports:
            async_mail:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: mail
            async_sms:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: sms

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async_mail
            App\Message\SmsNotification: async_sms
