name: Try Log Secrets

on:
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - name: log the secret
        run: echo ${{ secrets.MY_SECRET }}
      - name: Cache node_modules
        uses: actions/cache@v1
        id: yarn-cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-node-modules-
      - name: Yarn install
        if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
      - name: Yarn build
        run: yarn run encore production
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: public/build
